# Generated by Django 5.0.2 on 2024-03-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0002_gameinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='extra_text',
            field=models.CharField(blank=True, max_length=510),
        ),
    ]
