# Generated by Django 5.0.2 on 2024-03-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('game_time', models.CharField(max_length=64)),
                ('bgg_link', models.URLField()),
                ('category', models.ManyToManyField(to='gamelist.category')),
                ('game_mechanics', models.ManyToManyField(to='gamelist.gamemechanic')),
            ],
        ),
    ]
