# Generated by Django 5.0.2 on 2024-03-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'accepted'), (2, 'not accepted')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'accepted'), (2, 'not accepted')], default=0)),
            ],
        ),
    ]
